### ISSUE TITLE
Not possible to buy 10 mines

### ISSUE THREAD

**Issue by langerak** [RaymiiOrg/c_ookieclicker#5]
After selecting option 2 to buy 10x a upgrade I cannot buy 10 mines:

===== Store ====
[K]: buy 10 Cursors; cost: 4280 cookies;
[G]: buy 10 Grandmas; cost: 4040 cookies;
[F]: not enough cookies for 10 Farms (cost: 58540 cookies);
[m]: not enough cookies for Mine (cost: 13800 cookies);

Command + ↩:

**Comment by RaymiiOrg** [comment]
Should be fixed in 105, display code has been reworked.
